// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT91jmC0Fq0eNa1rKITPx0nNZfAc4jn4w',
    appId: '1:732054022817:web:8e2e97b5f295d8bb321ee0',
    messagingSenderId: '732054022817',
    projectId: 'satuabababca-943ee',
    authDomain: 'satuabababca-943ee.firebaseapp.com',
    storageBucket: 'satuabababca-943ee.firebasestorage.app',
    measurementId: 'G-M8KHN1Z9EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZjujKnsE-CNCs5n9VAKfYVv-t63Vp05g',
    appId: '1:732054022817:android:4538bb23fc5e0864321ee0',
    messagingSenderId: '732054022817',
    projectId: 'satuabababca-943ee',
    storageBucket: 'satuabababca-943ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9G1lrmelWmYvQ6XoLFapZeZnruGZtr0M',
    appId: '1:732054022817:ios:e1e25ba717b6aaa9321ee0',
    messagingSenderId: '732054022817',
    projectId: 'satuabababca-943ee',
    storageBucket: 'satuabababca-943ee.firebasestorage.app',
    iosBundleId: 'com.example.bcac',
  );
}
